---
- name: Assert that prerequisites exist
  tags: newrelic-release
  assert:
    that:
      - newrelic_pkg is defined
      - newrelic_ver is defined
      - newrelic_rel is defined
      - newrelic_baseurl is defined

- name: Execute mktemp
  tags: newrelic-release
  command: mktemp -u --suffix .rpm
  register: newrelic_mktemp

- name: Create temporary package
  tags: newrelic-release
  get_url: url={{ newrelic_fetch }}
           dest={{ newrelic_mktemp.stdout }}
  register: newrelic_get_url
  when: newrelic_mktemp|success

- name: Install newrelic-repo
  tags: newrelic-release
  yum: name={{ item }}
       state=present
  register: newrelic_yum
  with_items: "{{ newrelic_mktemp.stdout }}"
  when: newrelic_get_url|success

- name: Configure newrelic.repo
  tags: newrelic-release
  template: src=newrelic.repo.j2
            dest=/etc/yum.repos.d/newrelic.repo
            owner=root
            group=root
            mode=0644
  when: newrelic_yum|success

- name: Erase temporary package
  tags: newrelic-release
  file: path={{ newrelic_mktemp.stdout }}
        state=absent
  when:
    - newrelic_mktemp|success
    - newrelic_yum|success
