---
- name: Attempting to generate temporary file
  tags: newrelic
  tempfile:
    prefix: newrelic.
    state: file
    suffix: .rpm
  register: newrelic_tempfile

- name: Attempting to download package to temporary location
  tags: newrelic
  get_url:
    dest: "{{ newrelic_tempfile.path }}"
    force: yes
    url: "{{ newrelic_fetch }}"
  register: newrelic_get_url
  when: newrelic_tempfile is success

- name: Ensure that the {{ newrelic_pkg }} package is installed
  tags: newrelic
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: newrelic_yum
  with_items: "{{ newrelic_tempfile.path }}"
  when: newrelic_get_url is success

- name: Attempting to purge temporary package from the filesystem
  tags: newrelic
  file:
    path: "{{ newrelic_tempfile.path }}"
    state: absent
  when:
    - newrelic_tempfile is success
    - newrelic_yum is success

- name: Attempting to overlay newrelic repository configurations
  tags: newrelic
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: newrelic.repo.j2, dst: /etc/yum.repos.d/newrelic.repo }
  when: newrelic_yum is success

- name: Ensure that the newrelic gpg keys are installed
  tags: newrelic
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-NewRelic
    state: present
  when: newrelic_yum is success

- name: Ensure that the required newrelic packages are installed
  tags: newrelic
  become: true
  yum:
    disablerepo: "{{ newrelic_disablerepo|join(',') }}"
    enablerepo: "{{ newrelic_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ newrelic_packages }}"
  when:
    - newrelic_packages|length > 0
    - newrelic_yum is success
...
